// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// eslint-disable-next-line simple-import-sort/imports
import { defineConfig, env } from "prisma/config";
import "dotenv/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
